### PR TITLE
fix: allow WikiPage.#revisionAuthor to be undefined

### LINKED ISSUE #108: Errors creating/getting blank wiki pages
The source of the issue is that the assertion that data.revisionBy?.data is not null can fail here for wiki pages without a revision history: https://github.com/reddit/devvit/blob/9c982244e1b492eb9a7d015d63008c093d97c083/packages/public-api/src/apis/reddit/models/WikiPage.ts#L101

It affects both the `createWikiPage()` and `getWikiPage()` methods. The `revision_date`, `revision_id`, and `revision_id` properties returned by `/r/subreddit/wiki/somewikipage.json` can be null if it was created with no content and no other edits have been made since.

image
image

---

Reproduction:

1. Set up a Devvit button, form, etc

2. Run the following:  
```ts
await context.reddit.createWikiPage({
    content: "", // Create Wiki Page with empty content.
    page: "somenewwikipage", // Any valid wiki page as long as it hasn't been created yet
    subredditName: context.subredditName,
});
```

3. That will produce the following error:  
```
[ERROR] Nov 5 17:59:56 Error: Wiki page author details are missing
    at assertNonNull (main.js:11588:11)
    at new _WikiPage (main.js:27558:5)
    at _WikiPage.getPage (main.js:27656:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.formHandler4 [as onSubmit] (main.js:28242:29)
    at async Devvit.handleUIEvent [as HandleUIEvent] (main.js:17588:5)
    at async executeWithSourceMap (/srv/index.cjs:136468:12)
    at async /srv/index.cjs:122669:27
```

4. If you then visit the URL for the wiki page or check the moderation log, you can see that the page was in fact created.
image
image

5. You can then use the same wiki page to also replicate the getWikiPage() error:  
```ts
await context.reddit.getWikiPage(context.subredditName, "somenewwikipage");
```

6. That will produce the same error as in point 3.

---

It's worth noting that Devvit is not the only way to create these types of blank wiki pages. A user can also create this type of empty wiki page by navigating to `https://old.reddit.com/r/subreddit/wiki/create/somenewwikipage` and hitting submit without entering anything into the text field.

The issue is present in 0.11.2 and goes back at least as far as 0.10.16.

### PR DESCRIPTION
**Pull request by PitchforkAssistant**
Possibly fixes #108

## 💸 TL;DR
Allows WikiPage.#revisionAuthor to be undefined, as that is a possibility for some wiki pages.

## 📜 Details
Removes `assertNonNull(data.revisionBy?.data, 'Wiki page author details are missing');` from the WikiPage constructor and sets `#revisionAuthor` to be of type `User | undefined` depending on whether `data.revisionBy` exists. Updates `get revisionAuthor()` and `toJSON()` to reflect the type change.

It's worth noting that `revisionBy` is already marked as potentially undefined in the `WikiPage` interface from `@devvit/protos`. `revisionId` and `revisionDate` are not marked that way, but would also be returned as `null` by the Data API in this same edge case of a wiki page with no revision history.

## 🧪 Testing Steps / Validation
Untested, as I am unable to set up the environment to produce a successful build even with no changes. TypeScript language server doesn't show any new errors though. Additionally, there are no existing tests for WikiPage found in `/packages/public-api/src/apis/reddit/tests`.

## ✅ Checks

- [❌] CI tests (if present) are passing  
 Unable to test, see above.
- [❌] Adheres to code style for repo
 Prettier doesn't even pass on an unmodified `WikiPage.ts` file.
- [✅] Contributor License Agreement (CLA) completed if not a Reddit employee

### CODE REVIEW

**Review by shannon-feng — CHANGES_REQUESTED** [review]
nice fix! I was able to copy your changes into our internal repo (with a small revision, see comment) and test creating a blank wiki page without errors. 

> Untested, as I am unable to set up the environment to produce a successful build even with no changes.

I was also having trouble setting up the environment for this repo. I've logged an issue internally to investigate, seems like our README could use better instructions for env set-up and testing.

File: packages/public-api/src/apis/reddit/models/WikiPage.ts [hunk 1]
```diff
@@ -97,9 +97,7 @@ export class WikiPage {
     this.#revisionId = data.revisionId;
     this.#revisionDate = new Date(data.revisionDate * 1000); // data.revisionDate is represented in seconds, so multiply by 1000 to get milliseconds
     this.#revisionReason = data.reason ?? '';
-
-    assertNonNull(data.revisionBy?.data, 'Wiki page author details are missing');
-    this.#revisionAuthor = new User(data.revisionBy.data, metadata);
+    this.#revisionAuthor = data.revisionBy ? new User(data.revisionBy.data, metadata) : undefined;
```
[the remark this answers is not in the document]
Comment (PitchforkAssistant) [reply packages/public-api/src/apis/reddit/models/WikiPage.ts]: I just managed to get the package to compile on my machine. I pushed the fix to this issue to the repo and squashed it into the same commit.

I tested it by replacing the compiled WikiPage files in my test app's node_modules and it fixed the issue for me too.

**Comment by PitchforkAssistant** [comment]
Made the requested change now that I was finally able to compile and notice the issue with the undefined check.

And I agree that the README could use better instructions for compiling specific packages like the `public-api` one.  
I ended up clearing everything except that package, changing out several of its dependencies for valid @next versions (packages like the matching `@devvit/shared-types` and `@devvit/protos` are not included with this repo), and copying the `src/devvit/internals/semanticColors.ts` and `src/types/icons.js` files from an already published version because generating them requires dependencies that aren't public (`@reddit/faceplate-ui`).

File: packages/public-api/src/apis/reddit/models/WikiPage.ts [hunk 2]
```diff
@@ -97,9 +97,7 @@ export class WikiPage {
     this.#revisionId = data.revisionId;
     this.#revisionDate = new Date(data.revisionDate * 1000); // data.revisionDate is represented in seconds, so multiply by 1000 to get milliseconds
     this.#revisionReason = data.reason ?? '';
-
-    assertNonNull(data.revisionBy?.data, 'Wiki page author details are missing');
-    this.#revisionAuthor = new User(data.revisionBy.data, metadata);
+    this.#revisionAuthor = data.revisionBy?.data ? new User(data.revisionBy.data, metadata) : undefined;
```
Comment (shannon-feng) [inline packages/public-api/src/apis/reddit/models/WikiPage.ts:100]: Are you able to run `yarn lint:fix` in the `packages/public-api` directory? Doing that should auto-format the code with line breaks like:

```
    this.#revisionAuthor = data.revisionBy?.data
      ? new User(data.revisionBy.data, metadata)
      : undefined;
```

Comment (PitchforkAssistant) [reply packages/public-api/src/apis/reddit/models/WikiPage.ts]: I couldn't get that to work, all it did was generate a `.filesystem.json` file. Instead I ran prettier separately and only accepted its formatting change to my code (but none of the formatting changes it wanted to make to unrelated code in WikiPage.ts).

**Review by shannon-feng — APPROVED** [review]
LGTM, I'll plan to merge this Monday

**Review by pl00h — APPROVED** [review]
