### PR TITLE
fix: strip XML preamble in devvit create icons

### LINKED ISSUE #128: devvit create icons doesn't strip xml preamble
`devvit create icons` is supposed to convert svg files in the assets folder into usable image strings. That process results in an invalid svg if the file contains anything ahead of the `<svg>` tag.

The average svgfile will look something like this:

```xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" >
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" viewBox="0 0 300 300">
    <rect x="0" y="0" width="300" height="300" fill="red" />
</svg>
```

or this:

```
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 300">
    <rect x="0" y="0" width="300" height="300" fill="red" />
</svg>
```

In both examples, the data before the actual svg is retained in the output, resulting in something like this:

```ts
import {svg} from "@devvit/public-api";

export const Icons = {
  "exampleOne.svg": svg`<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" ><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" viewBox="0 0 300 300">    <rect x="0" y="0" width="300" height="300" fill="red" /></svg>`,
  "exampleTwo.svg": svg`<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 300">    <rect x="0" y="0" width="300" height="300" fill="red" /></svg>`,
} as const;
```

That results in the `svg` helper function logging "The provided string is not a valid SVG." and returning an empty string. Either the `devvit create icons` command or `svg` function needs to account for this, otherwise there is a lot of manual work required each time you regenerate the icons.

### PR DESCRIPTION
**Pull request by mvanhorn**
## Summary

Strips XML declarations and DOCTYPE tags from SVG files before inserting them into the generated icons map.

## Why this matters

[#128](https://github.com/reddit/devvit/issues/128) reports that `devvit create icons` produces broken icons when SVG files contain XML preambles. SVG editors like Illustrator and Inkscape commonly export files with `<?xml version="1.0" encoding="UTF-8"?>` before the `<svg>` tag. The `sanitizeSvg()` function in `@devvit/shared-types` checks `if (!svg.trim().startsWith('<svg'))` and returns `undefined` for these files, resulting in empty icon entries.

## Changes

In `packages/cli/src/commands/create/icons.ts`, added a regex strip in `#getSvgAssets()` that removes everything before the first `<svg` tag when reading each SVG file. This handles `<?xml?>` declarations, `<!DOCTYPE>` tags, and XML comments that precede the SVG element.

## Testing

The regex `contents.replace(/^[\s\S]*?(<svg)/i, '$1')` preserves the full `<svg>` element and everything inside it while stripping only content before the opening tag. SVG files without preambles are unaffected since the regex matches the `<svg` at position 0.

Fixes #128

This contribution was developed with AI assistance (Claude Code + Codex CLI).

### CODE REVIEW

File: packages/cli/src/commands/create/icons.ts [hunk 1]
```diff
@@ -58,7 +58,9 @@ export default class Icons extends DevvitCommand {
       assets.map(async (asset) => {
         const name = path.relative(assetsPath, asset);
         const contents = await fsp.readFile(asset, 'utf-8');
-        return { name, contents };
+        // Strip XML preamble (<?xml?>, <!DOCTYPE>, comments) before <svg> tag.
+        const stripped = contents.replace(/^[\s\S]*?(<svg)/i, '$1');
```
Comment (niedzielski) [inline packages/cli/src/commands/create/icons.ts]: would you mind extracting this to a standalone function and adding a few unit tests?

**Review by stephenoid — APPROVED** [review]
thanks!
