### PR TITLE
Fix NSFW property on User model and add missing properties

### LINKED ISSUE #193: User class nsfw getter not wokring
Image

User.nsfw always return false , even for nsfw profiles

### PR DESCRIPTION
**Pull request by fsvreddit**
Closes #193 

## 💸 TL;DR

This pull request addresses two issues on the `User` model:
* NSFW property is returning the wrong value - it currently returns the "I am over 18 and want to see NSFW content" property, rather than the "I am NSFW" property.
* Two underlying properties available on the Data API (isMod and isGold) are not available on the User model. I am now exposing these properly, using the current "Reddit Premium" terminology instead of Reddit Gold.

## 🧪 Testing Steps / Validation
I have tested these locally by modifying files in the node_modules folder. However it is not possible for me to run full CI on this.

For some time I have had my own User model that transforms these values in the same way.

## ✅ Checks

- [ ] CI tests (if present) are passing
- [X] Adheres to code style for repo
- [X] Contributor License Agreement (CLA) completed if not a Reddit employee

### CODE REVIEW

File: packages/reddit/src/models/User.ts [hunk 1]
```diff
@@ -242,8 +244,10 @@ export class User {
     // UserDataByAccountIds returns the ID without the t2_ prefix
     this.#id = T2(isT2(data.id) ? data.id : `t2_${data.id}`);
     this.#username = data.name;
-    this.#nsfw = data.over18 ?? false;
+    this.#nsfw = data.subreddit?.over18 ?? false;
     this.#isAdmin = data.isEmployee ?? false;
+    this.#isModerator = data.IsMod ?? false;
```
Comment (stephenoid) [inline packages/reddit/src/models/User.ts:249]: i'll tweak this to isMod locally.

File: packages/reddit/src/models/User.ts [hunk 2]
```diff
@@ -220,6 +220,8 @@ export class User {
   #commentKarma: number;
   #nsfw: boolean;
   #isAdmin: boolean;
+  #isModerator: boolean;
```
Comment (stephenoid) [inline packages/reddit/src/models/User.ts:223]: i think we're inconsistent, there's no fromJSON(), and toJSON() doesn't seem well-supported so i think omitting this state from fromJSON() is fine 👍

File: packages/reddit/src/models/User.ts
Comment (stephenoid) [inline packages/reddit/src/models/User.ts:1]: we're exploring rewriting public-api to use @devvit/reddit and these changes are minimal so i think leaving these changes only in @devvit/reddit is ok :+1:

**Review by stephenoid — APPROVED** [review]
looks good! thanks!
